# Problem 29: https://projecteuler.net/problem=29

# How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

# Solution: Python's "set" data structure will ensure we don't allow duplicates.

def sequenceLength(n):
    aMax = n
    bMax = n
    sequence = set()
    for a in range(2, aMax+1):
        for b in range(2, bMax+1):
            sequence.add(a**b)
    return aMax, len(sequence)

from time import time
from datetime import timedelta

stime = time()
n, nterms = sequenceLength(100)
etime = time()
elapsed = timedelta(seconds=etime - stime)
problem_name = "Problem 29"
print(f"{problem_name}: {n=}, {nterms=}.  Elapsed time={elapsed}")
