# Question: By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Solution: We could solve this by generating all the fibonacci numbers and adding the even ones, but we can do things a little faster
# It turns out that given the last two fibonacci numbers, the next one is generated by f_n = 4*f_n-1 + f_n-2


def evenFibSum(cap):
    ans = 0
    a= 1
    b = 1
    while b < cap:
        c = a + b
        a = b
        b = c
        if b%2 == 0:
            ans += b
    return ans


def fibNextEven(a, b):
    return 4*b + a

def fastEvenFibSum(cap):
    ans = 10
    a = 2
    b = 8
    c = 34
    while c < cap:
        ans += c
        a = b
        b = c
        c = fibNextEven(a, b)
    return ans

print(fastEvenFibSum(4000000))
